# Should the bot try to link to your terminal/console for commands?
enable-console: true

# Please copy your Discord API token here.
# If the token is set to "<none>", the bot will not load.
# If the token is invalid or discord does not allow it, the bot will not load.
api-token: "<none>"

# This is the Discord user ID of the bot owner. This may be used for certain commands.
bot-owner-id: "<none>"

# What is the Discord category ID for tickets?
ticket-category-id: "<none>"

# What is the Discord channel ID for ticket history?
ticket-history-channel-id: "<none>"

# What is the Discord role ID for the Support role?
support-role-id: "<none>"
